name: Application Test and Release Workflow

on:
  push:
    branches:
      - master

jobs:

  docker_hub_release:
    env:
        DOCKER_HUB: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_PWD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: docker login -u $DOCKER_HUB -p $DOCKER_HUB_KEY
      - run: docker build . -t enricmartos/flask-first-steps:latest
      - run: docker push enricmartos/flask-first-steps:latest
